Added ability to provide a default value.
tsolarin/readline pull request #8
Opened 2017-02-16 00:11 UTC by DewJunkie

Possibly this is out of scope, but I started using default values recently in my console programs, I don't know if this falls into the works like GNU readline, because I haven't used it as a developer, but I have noticed this used in other programs that I have used.
I will probably add as a static property a prompt suffix. ex ":", ">" or whatever suits the app.

This is my first pull request, so please point out anything wrong I did in the process if you have the time.

Thanks

2017-02-16 15:07 UTC, tsolarin commented
@DewJunkie thanks for this PR and I can understand what you're trying to do and how it will add value. However, how does this feature compare to a user doing this:
```
string input = ReadLine.Read("Would you like to continue [Y]:");
if (string.IsNullOrWhitespace(input)
    ....
else
    ....
```

2017-02-16 15:40 UTC, DewJunkie commented
It is exactly the same as what you mentioned, so it doesn't add anything not possible, just cleans it up.  I use a bit of console apps for testing/validation.  I have some users who just want to double click anything I send them, so my typical pattern is.  So if the goal is be like GNU readline, I could see it being out of scope.  My goal was, make my life easier with minimal change upstream.  It's totally understandable if they don't align.
```
app.exe --option1 a --option2 b --option3 c settings.json

// Loop
{
  // Show app menu
  app.option1 = ReadLine.Read("Prompt", app.option1);
  // etc...
}
```

2017-02-16 17:45 UTC, tonerdo requested changes
After giving it a bit of thought I figured that having a `defaultInput` will be a nice feature to have. However, let's not tie the developer in with a specific prompt closer or `defaultInput` print out format

2017-02-16 17:45 UTC, tsolarin commented on src/ReadLine/ReadLine.cs
> +
Let's remove the `PromptCloser`

2017-02-16 17:45 UTC, tsolarin commented on src/ReadLine/ReadLine.cs
> +            Console.Write(PromptCloser);
No need to print out the default input or prompt closer let the developer specify the output string format using the `prompt` parameter

2017-02-16 17:45 UTC, tsolarin commented on src/ReadLine/ReadLine.cs
> +            }
The defaultInput isn't being added to the history. Is this intentional?

2017-02-16 17:47 UTC, tsolarin commented
@DewJunkie This feature is super welcome I just have a couple of comments. I suggest you resolve merge conflicts first so that your changes are made on updated code and the CI tests can validate this PR

2017-02-18 08:03 UTC, tsolarin commented
@DewJunkie Checking in with you. Are you still looking into this?

2017-02-19 14:40 UTC, tsolarin commented
Are you still looking into this? /cc @DewJunkie

2017-02-20 00:22 UTC, DewJunkie commented
I was/am travelling for work, I am going to try and have the suggestions you made completed/checked in either later tonight, but possibly it will be the end of the week.

2017-02-20 05:01 UTC, DewJunkie commented
Ok I merged in the latest, and made the changes as discussed.  I don't know if the pull request is tied to a particular commit, or if it is from my master branch.  If I need to submit a new pull request and cancel this one, let me know.

2017-02-20 05:06 UTC, DewJunkie commented on src/ReadLine/ReadLine.cs
> +            }
As it is written "text" would be an empty string, I felt like adding the default to the history didn't make sense, and adding an empty value also would not make sense, and that is why I omit adding anything to history if the default value is used.  If we were going to go with 1 of the 2 options, adding the default value would be the better choice, but then hitting (up) would have something that you never typed in.

2017-02-20 15:27 UTC, tsolarin commented on src/ReadLine/ReadLine.xproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Let's just use `project.json` for now. This project will migrate to `csproj` when the dotnet cli comes out of preview

2017-02-20 15:28 UTC, tsolarin commented on .gitignore
> +/src/ReadLine/*.user
Just `*.user` should be sufficient and would cover all places it could occur in the future

2017-02-20 22:30 UTC, DewJunkie commented on src/ReadLine/ReadLine.xproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
removed as suggested.

2017-02-20 22:30 UTC, DewJunkie commented on .gitignore
> +/src/ReadLine/*.user
modified as suggested

2017-02-21 11:00 UTC, tonerdo approved these changes

2017-02-21 15:10 UTC, merged

2017-02-21 15:10 UTC, tsolarin commented
Thanks @DewJunkie 👍